name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Se dispara cuando haces push a la rama main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: api-chatbot-whitelabel-notificaciones
  REGION: us-central1
  # Esta es la SA que usará la API para Sheets (Runtime)
  RUNTIME_SA: sa-chatbot-whitelabel@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # Aquí va el JSON de la SA de CI/CD (la que creaste para desplegar)
          credentials_json: '${{ secrets.GCP_SA_KEY_DEPLOY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --service-account ${{ env.RUNTIME_SA }} \
            --allow-unauthenticated \
            --platform managed \
            --quiet